In [446]:
import pandas as pd
import numpy as np
from numpy import absolute
from numpy import mean
from numpy import std
from sklearn import preprocessing, metrics
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedKFold
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [447]:
df = pd.read_csv("datas.csv")
df = df.drop(['sPartialGraphProcess', 'sReduceExecution','sMinEdgetoProcess','sApprAttrValues','minProcessEdge','percentage'], axis=1)
df.dropna()
print(df.head())

   vertexNum  edgeNum  maxEdgeDegree  iterationNum  executionTime    Error
0      32768   524288           3877             6             14   0.0000
1      32768   524288           3877             5             10   0.0000
2      32768   524288           3877             4              9   0.0118
3      32768   524288           3877             3              8   0.7980
4      32768   524288           3877             2              5  33.1070


In [448]:
X = df.drop(['executionTime', 'Error'],axis=1)
y = df[['executionTime', 'Error']]

In [449]:
X = preprocessing.normalize(X)
#print(X)
#y = preprocessing.normalize(y)


x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=13)


"""sc_X = StandardScaler()
x_train=sc_X.fit_transform(x_train)
x_test=sc_X.transform(x_test)
print(x_test)
print(x_train)
print(y_train)
print(y_test)"""

'sc_X = StandardScaler()\nx_train=sc_X.fit_transform(x_train)\nx_test=sc_X.transform(x_test)\nprint(x_test)\nprint(x_train)\nprint(y_train)\nprint(y_test)'

In [450]:
model = LinearRegression()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 72.96656620129522
Mean Squared Error: 11705.863587122436
Root Mean Squared Error: 108.19363930990785


In [451]:
print(y_test)
print(y_pred)

    executionTime      Error
42            705   0.086000
4               5  33.107000
20            106   0.000000
50            695  11.890000
0              14   0.000000
14             50   0.000045
[[747.5067775    9.86250496]
 [146.38367793  43.48151552]
 [ 58.48658922   6.21455865]
 [956.29479167  10.12376536]
 [175.17654377 -45.66315715]
 [-90.64379975   7.28486709]]


In [452]:
model = KNeighborsRegressor()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 62.77040415
Mean Squared Error: 24598.780285569897
Root Mean Squared Error: 156.8399830577965


In [453]:
print(y_test)
print(y_pred)

    executionTime      Error
42            705   0.086000
4               5  33.107000
20            106   0.000000
50            695  11.890000
0              14   0.000000
14             50   0.000045
[[ 551.2         12.5081368]
 [   9.8         13.0964   ]
 [  97.8          3.3805838]
 [1215.2          9.6959318]
 [  11.          13.09436  ]
 [  42.           4.143146 ]]


In [454]:
model = DecisionTreeRegressor()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)
# evaluate the model and collect the scores
n_scores = cross_val_score(model, X, y, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)
# force the scores to be positive
n_scores = absolute(n_scores)
# summarize performance
print('MAE: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Mean Absolute Error: 62.10749262499999
Mean Squared Error: 28932.46766187971
Root Mean Squared Error: 170.09546631782902
MAE: 64.653 (34.234)


In [455]:
print(y_test)
print(y_pred)

    executionTime      Error
42            705   0.086000
4               5  33.107000
20            106   0.000000
50            695  11.890000
0              14   0.000000
14             50   0.000045
[[5.95000000e+02 1.04234473e+01]
 [8.00000000e+00 7.98000000e-01]
 [1.04000000e+02 2.90000000e-05]
 [1.27283333e+03 8.07994317e+00]
 [1.00000000e+01 0.00000000e+00]
 [5.20000000e+01 0.00000000e+00]]


In [456]:
sc_X = StandardScaler()
X_trainscaled=sc_X.fit_transform(x_train)
X_testscaled=sc_X.transform(x_test)
#X_trainscaled = x_train
#X_testscaled = x_test
#print(X_trainscaled)

In [493]:
#t = [(2),(3),(4),(5),(6),(7),(8),(9),(10),(2,2),(3,2),(4,2),(5,2),(6,2),(7,2),(8,2)]


model = MLPRegressor(hidden_layer_sizes=(4,8,5,12,8,4),activation="relu" ,random_state=1, max_iter=50000)
model.fit(X_trainscaled, y_train).loss_
print(model.loss_)
#print(model.loss_curve_)
print(model.n_outputs_)
print(model.best_loss_)
y_pred=model.predict(X_testscaled)


print(r2_score(y_pred, y_test))


2821.5213399150093
2
2802.035296428826
0.1659355145117689


In [494]:
print(y_test)
print(y_pred)
model.score(x_test, y_test)

    executionTime      Error
42            705   0.086000
4               5  33.107000
20            106   0.000000
50            695  11.890000
0              14   0.000000
14             50   0.000045
[[ 409.90114902   17.99250377]
 [   5.60958065   32.90427165]
 [ 161.08469893    7.68830165]
 [1032.1379004     6.23896257]
 [   8.70227582    9.24799178]
 [  39.67682943   14.14287613]]


-34.74991188325814

In [495]:
print("y1 MSE:%.4f" % mean_squared_error(y_test, y_pred)) 

#print("y2 MSE:%.4f" % mean_squared_error(y_test[:,1], y_pred[:,1]))

y1 MSE:17050.9915
